### ISSUE TITLE
Add alumni papers

### ISSUE THREAD

**Issue by quantum9Innovation** [Team-1280/eeXiv#6]
List provided below:

- ![HIST_2C_Term_Paper_-_Spencer_Level_-_Final_PDF.pdf](https://github.com/Team-1280/eeXiv/files/14290780/HIST_2C_Term_Paper_-_Spencer_Level_-_Final_PDF.pdf)

- ![SR_GKP___NeurIPS23_Paper2351_Camera_Ready.pdf](https://github.com/Team-1280/eeXiv/files/14303588/SR_GKP___NeurIPS23_Paper2351_Camera_Ready.pdf)

**Comment by Team1280Programming** [comment]
Closed as of fe1b72166dacee9f3a53b40d37c378469825fcdf
